#!/bin/bash
clear
sleep 0.3

# Frame 1 - one innocent frog, minding its business
cat << 'FRAME'


                              .-----.
                             ( o   o )
                             (  ~~~  )
                              '-----'
                             /       \
                            /         \

FRAME
sleep 0.8

# Frame 2 - something brewing...
clear
cat << 'FRAME'


                              .-----.
                             ( o   o )
                             (  ~~~  )
                              '-----'
                             /       \        ~
                            /         \   ~
                                          ~

FRAME
sleep 0.4

# Frame 3 - RIPS IT
clear
cat << 'FRAME'
                                                      ~  ~  ~
                                               ~  ~  ~  ~  ~
                                         ~  ~  ~  ~  ~  ~
                              .-----.~  ~  ~  ~  ~  ~  ~
                             ( O   O )~  ~  ~  ~  ~  ~  ~
                             (  ~~~  )oO~  ~  ~  ~  ~  ~  ~
                              '-----'    ~  ~  ~  ~  ~  ~
                             /       \      ~  ~  ~  ~
                            /         \

                    p  f  f  f  f  F  F  F  R  R  R  T  T  ! !

FRAME
sleep 0.7

# Frame 4 - aftermath, frog 2 hops in
clear
cat << 'FRAME'


               . . . . . . .
              .-----.  . . . . . . .                    .-----.
             ( x   x )  . . . . . .                   ( o   o )
             (  ~~~  )   . . . . .                     (  ~~~  )
              '-----'     . . . .                       '-----'
             /       \     . . .                       /       \
            /         \     . .                       /         \

                    heh.

FRAME
sleep 1.0

# Frame 5 - frog 2 sizes up the situation
clear
cat << 'FRAME'


              .-----.                                   .-----.
             ( -   - )                                 ( o   o )
             (  ~~~  )                                 (  ~~~  )
              '-----'                                   '-----'
             /       \                                 /       \
            /         \                               /         \    .

FRAME
sleep 0.5

# Frame 6 - frog 2 LETS IT GO
clear
cat << 'FRAME'
                                                                    ~  ~  ~
                                                             ~  ~  ~  ~
              .-----.                                .-----.    ~  ~  ~  ~  ~
             ( ^   ^ )                              ( O   O )~  ~  ~  ~  ~  ~
             (  ~~~  )                              (  ~~~  )oO~  ~  ~  ~  ~  ~
              '-----'                                '-----'    ~  ~  ~  ~  ~
             /       \                              /       \      ~  ~  ~
            /         \                            /         \

                                        B  B  R  R  A  A  A  P  P  ! ! !

FRAME
sleep 0.7

# Frame 7 - frog 3 wanders in, regrets it immediately
clear
cat << 'FRAME'


              .-----.      . . . . . . .              .-----.
             ( ^   ^ )   . . . . . . . .             ( x   x )
             (  ~~~  )  . . . . . . .                (  ~~~  )
              '-----'    . . . . .                    '-----'
             /       \    . . .                      /       \
            /         \    .                        /         \

                                      .-----.
                                     ( o   o )
                                     (  ~~~  )
                                      '-----'
                                     /       \
                       oh no...     /         \     what did i walk into

FRAME
sleep 1.2

# Frame 8 - frog 3 can't hold it
clear
cat << 'FRAME'


              .-----.                                   .-----.
             ( ^   ^ )                                 ( ^   ^ )
             (  ~~~  )                                 (  ~~~  )
              '-----'                                   '-----'
             /       \                                 /       \
            /         \                               /         \

                                      .-----.
                                     ( >   < )
                                     (  ~~~  )
                                      '-----'
                                     /       \
                                    /         \        oh no.
                                        .

FRAME
sleep 0.5

# Frame 9 - frog 3 DETONATES
clear
cat << 'FRAME'


              .-----.                                   .-----.
             ( ^   ^ )                                 ( ^   ^ )
             (  ~~~  )                                 (  ~~~  )
              '-----'                                   '-----'
             /       \                                 /       \
            /         \                               /         \

                                      .-----.
                                     ( X   X )
                                     (  ~~~  )
                                      '-----'
                                     /       \
                                    /         \
                                      ~ ~ ~ ~
                                   ~ ~ ~ ~ ~ ~
                                ~ ~ ~ ~ ~ ~ ~ ~
                             ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

                   F  F  F  W  W  O  O  O  M  M  P  P  P  ! ! ! !

FRAME
sleep 0.8

# Frame 10 - total wipeout
clear
cat << 'FRAME'

  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
  . .-----.  . . . . . . . . . . . . . . . . . . . . . . .-----.  . . . .
  .( x   x ) . . . . . . . . . . . . . . . . . . . . . . ( x   x ) . . .
  .(  ~~~  ) . . . . . . . . . . . . . . . . . . . . . . (  ~~~  ) . . .
  . '-----'  . . . . . . . . . . . . . . . . . . . . . .  '-----'  . . .
  ./       \ . . . . . . . . . . . . . . . . . . . . . . /       \ . . .
  /         \. . . . . . . . .-----.  . . . . . . . . . /         \. . .
  . . . . . . . . . . . . .  ( x   x ) . . . . . . . . . . . . . . . . .
  . . . . . . . . . . . . .  (  ~~~  ) . . . . . . . . . . . . . . . . .
  . . . . . . . . . . . . .   '-----'  . . . . . . . . . . . . . . . . .
  . . . . . . . . . . . . .  /       \ . . . . . . . . . . . . . . . . .
  . . . . . . . . . . . . . /         \. . . . . . . . . . . . . . . . .
  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

                            t o t a l   w i p e o u t

FRAME
sleep 1.5

# Frame 11 - dust settles. all three. gone.
clear
cat << 'FRAME'



              .-----.           .-----.           .-----.
             ( x   x )         ( x   x )         ( x   x )
             (  ~~~  )         (  ~~~  )         (  ~~~  )
              '-----'           '-----'           '-----'
             /       \         /       \         /       \
            /         \       /         \       /         \


              ...ribbit...     ...ribbit...     ...ribbit...


FRAME
echo ""
