#!/bin/bash
clear
sleep 0.3

# Frame 1 - one innocent frog
cat << 'FRAME'


                  @..@
                 (----)
                ( >__< )
                ^^ ~~ ^^
               ""      ""

FRAME
sleep 0.6

# Frame 2 - frog 1 lets one rip
clear
cat << 'FRAME'


                  @..@
                 (----)              ~
                ( >__< )  . ~ ~    ~
                ^^ ~~ ^^          ~
               ""      ""

FRAME
sleep 0.3

# Frame 3 - big cloud
clear
cat << 'FRAME'
                                                        ~  ~
                                              ~  ~    ~   ~
                                         ~ ~    ~ ~ ~  ~
                  @..@                 ~ ~ ~ ~ ~  ~  ~
                 (----)            ~ ~ ~ ~ ~  ~  ~
                ( O__O ) .oO~ ~ ~ ~ ~ ~ ~ ~    ~  ~  ~
                ^^ ~~ ^^      ~ ~ ~ ~ ~ ~ ~ ~ ~
               ""      ""       ~ ~ ~ ~ ~ ~  ~ ~  ~
                                    ~ ~ ~  ~  ~

                    p f f f f f F F F F R R R T T ! !
FRAME
sleep 0.6

# Frame 4 - aftermath, frog 2 hops in
clear
cat << 'FRAME'


                                                  . . . . .
                  x..x                .  .  .  .  .  .
                 (----)          .  .  .  .  .  .
                ( -__- )  ~~~  .  .  .  .  .
                ^^ ~~ ^^      .  .  .  .
               ""      ""
                                                            @..@
                                                           (----)
                               heh.                       ( o__o )
                                                          ^^ ~~ ^^
                                                         ""      ""
FRAME
sleep 0.8

# Frame 5 - frog 2 responds, frog 1 watches
clear
cat << 'FRAME'


                  @..@
                 (----)
                ( ^__^ )                                    @..@
                ^^ ~~ ^^                                   (----)
               ""      ""                                 ( >__< )  .
                                                          ^^ ~~ ^^
                                                         ""      ""

FRAME
sleep 0.4

# Frame 6 - frog 2 blasts
clear
cat << 'FRAME'
                                                                                   ~  ~
                                                                            ~   ~    ~
                  @..@                                                   ~ ~ ~  ~
                 (----)                                               ~ ~ ~  ~
                ( ^__^ )                                    @..@   ~ ~ ~ ~  ~  ~
                ^^ ~~ ^^                                   (----)~ ~ ~ ~ ~  ~
               ""      ""                                 ( O__O ) .oO~ ~ ~ ~ ~
                                                          ^^ ~~ ^^   ~ ~ ~ ~ ~ ~
                                                         ""      ""    ~ ~ ~  ~

                                                   B B R R R A A A P P P P ! ! !
FRAME
sleep 0.6

# Frame 7 - frog 3 arrives from below, both originals look smug
clear
cat << 'FRAME'


                  @..@                                                  . . . . .
                 (----)                                    x..x    . . .  .  .
                ( ^__^ )                                  (----)  .  .  .  .
                ^^ ~~ ^^                                 ( -__- ) ~~~  .  .
               ""      ""                                ^^ ~~ ^^
                                                        ""      ""

                                    @..@
                                   (----)
                          oh no   ( o__o )   what did i walk into
                                  ^^ ~~ ^^
                                  ""      ""
FRAME
sleep 1.0

# Frame 8 - frog 3 can't hold it either
clear
cat << 'FRAME'

                  @..@                                      @..@
                 (----)                                    (----)
                ( ^__^ )                                  ( ^__^ )
                ^^ ~~ ^^                                  ^^ ~~ ^^
               ""      ""                               ""      ""

                                    @..@
                                   (----)
                                  ( >__< )   oh no
                                  ^^ ~~ ^^
                                  ""      ""
                                       .
FRAME
sleep 0.4

# Frame 9 - frog 3 erupts DOWNWARD
clear
cat << 'FRAME'

                  @..@                                      @..@
                 (----)                                    (----)
                ( O__O )                                  ( O__O )
                ^^ ~~ ^^                                  ^^ ~~ ^^
               ""      ""                               ""      ""

                                    @..@
                                   (----)
                                  ( X__X )
                                  ^^ ~~ ^^
                                  ""      ""
                                  ~ ~ . ~ ~
                               ~ ~ ~ .o. ~ ~ ~
                            ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
                         ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
                       ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

              F  F  F  F  F  W  W  O  O  O  O  M  M  P  P  P  ! ! ! !
FRAME
sleep 0.7

# Frame 10 - total destruction
clear
cat << 'FRAME'

        .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
     .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
   .  .  .  x..x .  .  .  .  .  .  .  .  .  .  .  .  .  .  .x..x .  .  .  .
  .  .  .  (----).  .  .  .  .  .  .  .  .  .  .  .  .  .  .(----).  .  .  .
 .  .  .  ( x__x ) .  .  .  .  .  .  .  .  .  .  .  .  .  ( x__x ) .  .  .
  .  .  .  ^^ ~~ ^^ .  .  .  .  .  .  .  .  .  .  .  .  .  ^^ ~~ ^^.  .  .
   .  .  . ""    "" .  .  .  .  .  .  .  .  .  .  .  .  .  ""    "".  .  .
    .  .  .  .  .  .  .  .  .  x..x  .  .  .  .  .  .  .  .  .  .  .  .
      .  .  .  .  .  .  .  .  (----) .  .  .  .  .  .  .  .  .  .  .
        .  .  .  .  .  .  .  ( x__x ).  .  .  .  .  .  .  .  .  .
          .  .  .  .  .  .  . ^^ ~~ ^^.  .  .  .  .  .  .  .  .
            .  .  .  .  .  . ""    "" .  .  .  .  .  .  .  .
              .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
                 .  .  .  .  .  .  .  .  .  .  .  .  .
                    .  .  .  .  .  .  .  .  .  .  .

                          t o t a l   w i p e o u t
FRAME
sleep 1.5

# Frame 11 - dust settles, all three look pleased
clear
cat << 'FRAME'




                  @..@                @..@                  @..@
                 (----)              (----)                 (----)
                ( ^__^ )            ( ^__^ )              ( ^__^ )
                ^^ ~~ ^^            ^^ ~~ ^^              ^^ ~~ ^^
               ""      ""         ""      ""             ""      ""


                       ...ribbit...   ...ribbit...   ...ribbit...

FRAME
echo ""
