#!/usr/bin/env bash
# timmy — prints Timmy Burch from South Park with a TIMMAAAY! banner
# Usage: timmy [exit_code]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BANNER='
 ______  __  __  __    __  __    __  ______  ______  __  __
/\__  _\/\ \/\ \/\ "-./  \/\ "-./  \/\  __ \/\  __ \/\ \_\ \
\/_/\ \/\ \ \_\ \ \ \-./\ \ \ \-./\ \ \  __ \ \  __ \ \____ \
   \ \_\ \ \_____\ \_\ \ \_\ \_\ \ \_\ \_\ \_\ \_\ \_\/\_____\
    \/_/  \/_____/\/_/  \/_/\/_/  \/_/\/_/\/_/\/_/\/_/\/_____/

  ! ! !  T  I  M  M  A  A  A  A  A  A  A  Y  ! ! !'

YELLS=(
    "TIMMAY!"
    "TIMMAAAY!"
    "TIIIIMMMAAAAYYY!"
    "T I M M A A A A A Y ! ! !"
    "...timm... TIMMAAAY!"
    "TIMMAY! TIMMAY TIMMAY!"
)

if [ -t 1 ]; then
  ORANGE="\033[38;5;208m"
  RESET="\033[0m"
else
  ORANGE=""
  RESET=""
fi

ART1=$(cat "$SCRIPT_DIR/timmy1.txt")
ART2=$(cat "$SCRIPT_DIR/timmy 2.txt")

ARTS=("$ART1" "$ART2")
ART="${ARTS[$((RANDOM % 2))]}"
YELL="${YELLS[$((RANDOM % ${#YELLS[@]}))]}"

echo ""
echo -e "${ORANGE}${ART}${RESET}"
echo ""
echo "${BANNER}"
echo ""
echo "  ${YELL}"
echo ""

exit "${1:-0}"
